name: Lint and Test

on:
  push:
    branches:
      - develop
  pull_request:
    branches:
      - develop

jobs:
  lint_and_test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Lint and Test
        uses: ./.github/actions/lint-and-test
        with:
          node-version: '18'
