name: Test

on:
  push:
    branches:
      - develop
  pull_request:
    branches:
      - develop

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Install dependencies
        uses: ./.github/workflows/install-dependencies.yml

      - name: Run Tests
        run: npm run test:coverage
